name: Build CherryGram Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ORG_GRADLE_JVMARGS: "-Xmx6g -Xss32m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 1

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Install C++ Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y yasm nasm ninja-build ccache golang

      - name: Prepare Environment (Free up Space)
        run: |
          sudo apt-get remove -y '^llvm-.*' 'php.*' '^mongodb-.*' '^mysql-.*' azure-cli firefox mono-devel
          sudo apt-get autoremove -y
          sudo apt-get clean
          sudo rm -rf /usr/share/dotnet/ /usr/local/graalvm/ /usr/local/lib/node_modules
          df -h

      - name: Prepare Configuration Files
        run: |
          mkdir -p TMessagesProj/src/main/java/uz/unnarsx/cherrygram
          cat << 'EOF' > TMessagesProj/src/main/java/uz/unnarsx/cherrygram/Extra.kt
          package uz.unnarsx.cherrygram

          object Extra {
              const val APP_ID = ${{ secrets.APP_ID }}
              const val APP_HASH = "${{ secrets.APP_HASH }}"
          }
          EOF
          
          cp secrets_for_ci.env.example secrets_for_ci.env
          echo "All configuration files setup successfully!"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Release APK (Standalone)
        run: ./gradlew :TMessagesProj_AppStandalone:assembleRelease --no-daemon --info

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: CherryGram-Release-APK
          path: TMessagesProj_AppStandalone/build/outputs/apk/release/*.apk
