name: Build CherryGram Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ORG_GRADLE_JVMARGS: "-Xmx6g -Xss32m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 1

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Prepare Environment (Free up Space)
        run: |
          sudo apt-get remove -y '^llvm-.*' 'php.*' '^mongodb-.*' '^mysql-.*' azure-cli firefox mono-devel
          sudo apt-get autoremove -y
          sudo apt-get clean
          sudo rm -rf /usr/share/dotnet/ /usr/local/graalvm/ /usr/local/lib/node_modules
          df -h

      - name: Smart Setup API Keys
        run: |
          # 1. Poore project mein Extra.kt dhoondho (Bina exact path ke)
          EXTRA_FILE=$(find . -iname "Extra.kt" | head -n 1)
          
          # 2. Agar .example file hui toh usko use kar lo
          if [ -z "$EXTRA_FILE" ]; then
            EXAMPLE_FILE=$(find . -iname "Extra.kt.example" | head -n 1)
            if [ -n "$EXAMPLE_FILE" ]; then
              EXTRA_FILE="${EXAMPLE_FILE%.example}"
              cp "$EXAMPLE_FILE" "$EXTRA_FILE"
            fi
          fi
          
          echo "Editing File: $EXTRA_FILE"
          
          # 3. Dummy variables ko teri asli API keys se replace karo
          sed -i 's/APP_ID = 0/APP_ID = ${{ secrets.APP_ID }}/g' "$EXTRA_FILE"
          sed -i 's/APP_HASH = ""/APP_HASH = "${{ secrets.APP_HASH }}"/g' "$EXTRA_FILE"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Release APK (Standalone)
        run: ./gradlew :TMessagesProj_AppStandalone:assembleRelease --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: CherryGram-Release-APK
          path: TMessagesProj_AppStandalone/build/outputs/apk/release/*.apk
